In [1]:
pip install pandas

Requirement already satisfied: pandas in c:\users\anjan\appdata\local\programs\python\python312\lib\site-packages (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in c:\users\anjan\appdata\local\programs\python\python312\lib\site-packages (from pandas) (2.0.1)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\anjan\appdata\local\programs\python\python312\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\anjan\appdata\local\programs\python\python312\lib\site-packages (from pandas) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\anjan\appdata\local\programs\python\python312\lib\site-packages (from pandas) (2024.1)
Requirement already satisfied: six>=1.5 in c:\users\anjan\appdata\local\programs\python\python312\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 24.0 -> 25.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [2]:
import pandas as pd

In [3]:
df=pd.read_csv("train.csv")

In [4]:
df

          id  label                                              tweet
0          1      0   @user when a father is dysfunctional and is s...
1          2      0  @user @user thanks for #lyft credit i can't us...
2          3      0                                bihday your majesty
3          4      0  #model   i love u take with u all the time in ...
4          5      0             factsguide: society now    #motivation
...      ...    ...                                                ...
31957  31958      0  ate @user isz that youuu?ðððððð...
31958  31959      0    to see nina turner on the airwaves trying to...
31959  31960      0  listening to sad songs on a monday morning otw...
31960  31961      1  @user #sikh #temple vandalised in in #calgary,...
31961  31962      0                   thank you @user for you follow

[31962 rows x 3 columns]

In [5]:
df['tweet'].replace({1:"Positive",0:"Neutral",-1:"Negative"},inplace=True)

C:\Users\anjan\AppData\Local\Temp\ipykernel_10056\3810678019.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['tweet'].replace({1:"Positive",0:"Neutral",-1:"Negative"},inplace=True)

In [6]:
df

          id  label                                              tweet
0          1      0   @user when a father is dysfunctional and is s...
1          2      0  @user @user thanks for #lyft credit i can't us...
2          3      0                                bihday your majesty
3          4      0  #model   i love u take with u all the time in ...
4          5      0             factsguide: society now    #motivation
...      ...    ...                                                ...
31957  31958      0  ate @user isz that youuu?ðððððð...
31958  31959      0    to see nina turner on the airwaves trying to...
31959  31960      0  listening to sad songs on a monday morning otw...
31960  31961      1  @user #sikh #temple vandalised in in #calgary,...
31961  31962      0                   thank you @user for you follow

[31962 rows x 3 columns]

In [7]:
pip install nltk

Requirement already satisfied: nltk in c:\users\anjan\appdata\local\programs\python\python312\lib\site-packages (3.9.1)
Requirement already satisfied: click in c:\users\anjan\appdata\local\programs\python\python312\lib\site-packages (from nltk) (8.1.7)
Requirement already satisfied: joblib in c:\users\anjan\appdata\local\programs\python\python312\lib\site-packages (from nltk) (1.4.2)
Requirement already satisfied: regex>=2021.8.3 in c:\users\anjan\appdata\local\programs\python\python312\lib\site-packages (from nltk) (2024.11.6)
Requirement already satisfied: tqdm in c:\users\anjan\appdata\local\programs\python\python312\lib\site-packages (from nltk) (4.67.1)
Requirement already satisfied: colorama in c:\users\anjan\appdata\local\programs\python\python312\lib\site-packages (from click->nltk) (0.4.6)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 24.0 -> 25.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [8]:
import nltk
from nltk.tokenize import word_tokenize, sent_tokenize

In [9]:
from nltk.corpus import stopwords

In [10]:
nltk.download('punkt')  
nltk.download('punkt_tab') 
nltk.download('stopwords')

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\anjan\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package punkt_tab to
[nltk_data]     C:\Users\anjan\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\anjan\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [11]:
!kaggle datasets download -d abdallahwagih/spam-emails  
!unzip spam-emails.zip

'kaggle' is not recognized as an internal or external command,
operable program or batch file.

'unzip' is not recognized as an internal or external command,
operable program or batch file.

In [12]:
import pandas as pd

In [13]:
df = pd.read_csv("train.csv")

In [14]:
import re

In [15]:
cleaned = []

In [16]:
for text in df['tweet']:  
    cleaned_text = re.sub(r'[^\w\s]', '', text) 
    cleaned_text = re.sub(r'\s+', ' ', cleaned_text)  
    cleaned_data = cleaned_text.strip() 
    cleaned.append(cleaned_data)

In [17]:
tokens = [word_tokenize(x) for x in cleaned]

In [18]:
stop = set(stopwords.words('english'))

In [19]:
stpktn = []

In [20]:
for k in range(len(df['tweet'])):  
    p = [i for i in tokens[k] if i not in stop]  
    stpktn.append(p)

In [21]:
from nltk.stem import PorterStemmer
ps = PorterStemmer()

In [22]:
stemed_data = []
for Text in stpktn:
  stm = [ps.stem(word) for word in Text]
  stemed_data.append(stm)

In [24]:
stemed_data

[['user', 'father', 'dysfunct', 'selfish', 'drag', 'kid', 'dysfunct', 'run'],
 ['user',
  'user',
  'thank',
  'lyft',
  'credit',
  'cant',
  'use',
  'caus',
  'dont',
  'offer',
  'wheelchair',
  'van',
  'pdx',
  'disapoint',
  'getthank'],
 ['bihday', 'majesti'],
 ['model', 'love', 'u', 'take', 'u', 'time', 'urð', 'ðððð', 'ððð'],
 ['factsguid', 'societi', 'motiv'],
 ['22',
  'huge',
  'fan',
  'fare',
  'big',
  'talk',
  'leav',
  'chao',
  'pay',
  'disput',
  'get',
  'allshowandnogo'],
 ['user',
  'camp',
  'tomorrow',
  'user',
  'user',
  'user',
  'user',
  'user',
  'user',
  'user',
  'dannyâ'],
 ['next',
  'school',
  'year',
  'year',
  'examsð',
  'cant',
  'think',
  'ð',
  'school',
  'exam',
  'hate',
  'imagin',
  'actorslif',
  'revolutionschool',
  'girl'],
 ['love',
  'land',
  'allin',
  'cav',
  'champion',
  'cleveland',
  'clevelandcavali',
  'â'],
 ['user', 'user', 'welcom', 'im', 'gr8'],
 ['â',
  'ireland',
  'consum',
  'price',
  'index',
  'mom',
  'climb',
  'previou',
  '02',
  '05',
  'may',
  'blog',
  'silver',
  'gold',
  'forex'],
 ['selfish',
  'orlando',
  'standwithorlando',
  'pulseshoot',
  'orlandoshoot',
  'biggerproblem',
  'selfish',
  'heabreak',
  'valu',
  'love'],
 ['get', 'see', 'daddi', 'today', '80day', 'gettingf'],
 ['user',
  'cnn',
  'call',
  'michigan',
  'middl',
  'school',
  'build',
  'wall',
  'chant',
  'tcot'],
 ['comment',
  'australia',
  'opkillingbay',
  'seashepherd',
  'helpcovedolphin',
  'thecov',
  'helpcovedolphin'],
 ['ouchjunior', 'angryðgot7', 'junior', 'yugyoem', 'omg'],
 ['thank', 'paner', 'thank', 'posit'],
 ['retweet', 'agre'],
 ['friday',
  'ð',
  'smile',
  'around',
  'via',
  'ig',
  'user',
  'user',
  'cooki',
  'make',
  'peopl'],
 ['know', 'essenti', 'oil', 'made', 'chemic'],
 ['euro2016',
  'peopl',
  'blame',
  'ha',
  'conced',
  'goal',
  'fat',
  'rooney',
  'gave',
  'away',
  'free',
  'kick',
  'know',
  'bale',
  'hit'],
 ['sad',
  'littl',
  'dude',
  'badday',
  'coneofsham',
  'cat',
  'piss',
  'funni',
  'laugh'],
 ['product',
  'day',
  'happi',
  'man',
  'wine',
  'tool',
  'who',
  'weekend',
  'time',
  'open',
  'amp',
  'drink'],
 ['user', 'user', 'lumpi', 'say', 'prove', 'lumpi'],
 ['user',
  'tgif',
  'ff',
  'gamedev',
  'indiedev',
  'indiegamedev',
  'squad',
  'user',
  'user',
  'user',
  'user',
  'user'],
 ['beauti',
  'sign',
  'vendor',
  '80',
  '4500',
  'upsideofflorida',
  'shopalyssa',
  'love'],
 ['user',
  'smile',
  'media',
  'ðð',
  'pressconfer',
  'antalya',
  'turkey',
  'sunday',
  'throwback',
  'love',
  'ððâï'],
 ['great', 'panel', 'mediat', 'public', 'servic', 'ica16'],
 ['happi', 'father', 'day', 'user', 'ðððð'],
 ['50',
  'peopl',
  'went',
  'nightclub',
  'good',
  'night',
  '1',
  'man',
  'action',
  'mean',
  'peopl',
  'lost',
  'famili',
  'forev',
  'riporlando'],
 ['never',
  'chanc',
  'vote',
  'presidenti',
  'candid',
  'excit',
  'cycl',
  'look',
  'differ'],
 ['alohafriday',
  'time',
  'exist',
  'positivevib',
  'hawaiian',
  'user',
  'user',
  'user',
  'user'],
 ['user',
  'rip',
  'fellow',
  'nohern',
  'ireland',
  'fan',
  'sadley',
  'pass',
  'away',
  'tonight',
  'gawa',
  'forev',
  'sing',
  'cheer',
  'fire'],
 ['hard',
  'monday',
  'due',
  'cloudi',
  'weather',
  'disabl',
  'oxygen',
  'product',
  'today',
  'goodnight',
  'badmonday'],
 ['unbeliev',
  '21st',
  'centuri',
  'wed',
  'need',
  'someth',
  'like',
  'neverump',
  'xenophobia'],
 ['taylorswift1989', 'bull', 'domin', 'bull', 'direct', 'whatev', 'want', 'w'],
 ['morn', 'travelingram', 'dalat', 'ripinkylif'],
 ['user',
  'one',
  'word',
  'tell',
  'photoshop',
  'enoughisenough',
  'dontphotoshopeveryth',
  'wheresallthenaturalphoto'],
 ['oh',
  'cedarpoint',
  'wait',
  '2',
  'hour',
  'valravn',
  'line',
  'stop',
  'work',
  'close'],
 ['thank', 'sunshin', 'thank', 'posit'],
 ['final',
  'finish',
  'book',
  'youv',
  'work',
  'awhil',
  'bookworm',
  'ontothenextnovel'],
 ['yup',
  'knick',
  'fan',
  'hard',
  'easier',
  'nba',
  'fan',
  'playoff',
  'roll',
  'around',
  'ð'],
 ['life', 'social', 'network', 'embrac', 'day'],
 ['mom',
  'share',
  'bihday',
  'user',
  'bihday',
  'snake',
  'see',
  'weekend',
  'ðð¼'],
 ['love',
  'echeveria',
  'bloomsflow',
  'grow',
  'garden',
  'iphonesia',
  'bliss',
  'bloom',
  'basilicabotanica'],
 ['amaz', 'i_am', 'posit', 'affirm'],
 ['model', 'love', 'u', 'take', 'u', 'time', 'urð', 'ðððð', 'ððð'],
 ['whenev', 'im', 'someth', 'goe', 'wrong'],
 ['feel', 'blue', 'illustr'],
 ['best', 'pa', 'life', 'know', 'ðâïð¼ð', 'â'],
 ['abc2020',
  'get',
  'readi',
  '2',
  'remov',
  'victum',
  'frm',
  'pulseclub',
  'prayfororlando'],
 ['bihday',
  'got',
  'nose',
  'job',
  'user',
  'ððððð',
  'bihday',
  'petunia',
  'love',
  'ð'],
 ['concelebr', 'albanpilgrimag', 'first', 'time', 'user'],
 ['user', 'let', 'scumbaggeri', 'begin'],
 ['thank',
  'ðð',
  'super',
  'love',
  'âï',
  'zpamdelacruz',
  'wed',
  'dolor',
  'capa',
  'tarlac'],
 ['scourg', 'play', 'baroqu', 'piec', 'piano', 'beyond', 'belief'],
 ['user', 'let', 'fight', 'love', 'peac'],
 ['happi',
  'fatherâ',
  'day',
  'mr',
  'rayo',
  'video',
  'father',
  'day',
  'rayo',
  'world',
  'hotvideo',
  'video'],
 ['user',
  'ascot',
  'time',
  'babe',
  'âïâï',
  'ascot',
  'fashion',
  'monochrom',
  'style',
  'instahappyday'],
 ['weekendi', 'hereððððð', 'selfi', 'yolo', 'xoxo', 'like4lik'],
 ['happi',
  'work',
  'confer',
  'right',
  'mindset',
  'lead',
  'cultureofdevelop',
  'organ',
  'work',
  'mindset'],
 ['christina',
  'grimmi',
  'last',
  'perform',
  'shot',
  'via',
  'user',
  'christinarip',
  'voic',
  'christinagrimmi'],
 ['readi', 'danc', 'roar', 'preschool', 'student', 'proudâ'],
 ['youv', 'realli', 'hu', 'feel'],
 ['user',
  'wife',
  'ador',
  'miss',
  'poland',
  'show',
  'surgeri',
  'name',
  'bridget',
  'amp',
  'she',
  'everyth'],
 ['user', 'jealou', 'right', 'chatiado'],
 ['celebr', 'everi', 'man', 'play', 'fatherli', 'role', 'father', 'day'],
 ['im', 'sure', 'happi', 'ðð½ðð½ðð½', 'hour'],
 ['ðthe',
  'white',
  'establish',
  'cant',
  'blk',
  'folx',
  'run',
  'around',
  'love',
  'promot',
  'great'],
 ['good',
  'morn',
  'journey',
  'begin',
  'ðððð³',
  'travel',
  'yeah',
  'thejourneybegin',
  'helloâ'],
 ['user', 'luv', 'hottweet', 'like', 'â', 'âvenusexchangeâ'],
 ['new', 'brochur', 'arriv', 'excit', 'awork', 'solut'],
 ['much',
  'stuff',
  'happen',
  'florida',
  'first',
  'orlando',
  'shoot',
  'disneygatorattack',
  'two',
  'year',
  'old',
  'kidðð'],
 ['user',
  'ferrari',
  'itðªð¼',
  'sake',
  'championship',
  'gp',
  'clearli',
  'turn',
  'point',
  'rb',
  'ferrarimercsð'],
 ['ace', 'first', 'test', 'proud'],
 ['seek', 'probe', 'udtapunjab', 'leak', 'point', 'finger', 'amarind', 'aap'],
 ['user', 'wrap', 'senseaboutmath', 'user', '6th', 'user', 'user', 'user'],
 ['user',
  'hey',
  'white',
  'peopl',
  'call',
  'peopl',
  'white',
  'user',
  'race',
  'ident',
  'medâ'],
 ['user',
  'user',
  'might',
  'shown',
  'today',
  'regurgit',
  'talk',
  'point',
  'name',
  'call'],
 ['sometim',
  'rais',
  'brow',
  'rais',
  'bar',
  'golfstrengthandcondit',
  'strong',
  'felixfoisgolf'],
 ['ððð', 'greathonour', 'careerconvo', 'user', 'user'],
 ['user',
  'design',
  'innov',
  'learn',
  'space',
  'user',
  'includ',
  'wateringhol',
  'cave',
  'mountaintop',
  'campfir',
  'user',
  'hâ'],
 ['altright', 'use', 'amp', 'insecur', 'lure', 'men', 'whitesupremaci'],
 ['carri',
  'gun',
  'wouldnt',
  'help',
  'cant',
  'take',
  'gun',
  'control',
  'wont',
  'stop',
  'black',
  'market',
  'terror',
  'get',
  'wors'],
 ['use', 'power', 'mind', 'heal', 'bodi', 'altwaystoh', 'healthi', 'peac'],
 ['woohoo', '5', 'week', 'go'],
 ['far', 'away', 'place', 'famili', 'member', 'hu'],
 ['readi',
  'rehears',
  'tonight',
  'new',
  'music',
  'new',
  'video',
  'look',
  'announc',
  'midweek',
  'newmus',
  'watchthisspac',
  'guitar'],
 ['monday', 'night', '8pm', 'channel', 'final', 'get', 'see', 'fuss'],
 ['watch', 'new', 'episod', 'user', 'user'],
 ['user',
  'offlin',
  'nice',
  'long',
  'night',
  'ð',
  'snapchat',
  'user',
  'redhead',
  'vermillionr'],
 ['15', 'thing', 'incred', 'peopl'],
 ['ye',
  'receiv',
  'accept',
  'letter',
  'master',
  'back',
  'user',
  'octob',
  'goodtim',
  'histori'],
 ['daughter',
  'ride',
  'bike',
  'around',
  'driveway',
  'son',
  'play',
  'guitar',
  'us',
  'enjoy',
  'ðº',
  'campfir',
  'summeim',
  'memori'],
 ['omg',
  'love',
  'station',
  'way',
  'jam',
  'work',
  'get',
  'work',
  'done',
  'cours',
  'memori',
  'user'],
 ['user',
  'ill',
  'alway',
  'hope',
  'one',
  'day',
  'ill',
  'get',
  'hug',
  'dont',
  'think',
  'gon',
  'na',
  'happen',
  'anytim',
  'soon'],
 ['model', 'love', 'u', 'take', 'u', 'time', 'urð', 'ðððð', 'ððð'],
 ['coupl', 'sex', 'fat', 'nake', 'japanes', 'girl'],
 ['hump', 'hump', 'day', 'humpersð', 'edwardsvil', 'pennsylvania'],
 ['personalis', 'gbp', '799', 'get', 'shop', 'cool', 'home', 'fun'],
 ['truli', 'sick', 'ppl'],
 ['trump',
  'call',
  'obama',
  'resign',
  'orlando',
  'shoot',
  'boy',
  'point',
  '8',
  'year',
  'talk',
  'chang'],
 ['user',
  'user',
  'user',
  'user',
  'long',
  'nashvilletour2016',
  'nashvilleforev',
  'ððð'],
 ['â',
  'eurusd',
  'clear',
  '11400',
  'barrier',
  'jump',
  'fresh',
  '4week',
  'high',
  'blog',
  'silver',
  'gold',
  'forex'],
 ['go', 'la', 'tomorrow'],
 ['thank', 'good', 'friend', 'thank', 'posit'],
 ['still',
  'wrap',
  'head',
  'around',
  'fact',
  'christinagrimmi',
  'gone',
  'fact',
  'man',
  'destroy',
  'prayfororlando'],
 ['receiv',
  'di',
  'user',
  'cant',
  'wait',
  'sta',
  'bake',
  'eyelid',
  'ðððððð',
  'ðððâ'],
 ['play', 'vigilfororlando', 'harp', 'clonakilti', 'rip', 'via', 'user'],
 ['user', 'ye', 'ye', 'ye', 'ihavenofriend', 'someonecomewithm'],
 ['sundayð',
  'weekend',
  'relax',
  'icon',
  'woman',
  'sundaymorn',
  'sunday',
  'marilynmonro'],
 ['user',
  'im',
  'interest',
  'linguist',
  'doesnt',
  'address',
  'race',
  'amp',
  'racism',
  'power',
  'raciolinguist',
  'bringsâ'],
 ['one', 'belov', 'long', 'lost', 'cd', 'recov', 'thank', 'appl', 'music'],
 ['marvel',
  'song',
  'musica',
  'weed',
  'ripchristina',
  'adel',
  'danc',
  'vine',
  'user'],
 ['user',
  'user',
  'mock',
  'obama',
  'black',
  'user',
  'user',
  'user',
  'user',
  'brexit'],
 ['â',
  'spell',
  'brexit',
  'referendum',
  'commerzbank',
  'blog',
  'silver',
  'gold',
  'forex'],
 ['100', 'amaz', 'health', 'benefit', 'cucumb', 'healthi', 'altwaystoh'],
 ['model', 'love', 'u', 'take', 'u', 'time', 'urð', 'ðððð', 'ððð'],
 ['work',
  'ðªððð¼',
  'ofw',
  'pinoy',
  'followm',
  'iger',
  'instagood',
  'smile',
  'love'],
 ['toradora', 'anim', 'animeedit', 'made', 'breakup', 'alon', 'lone'],
 ['50',
  'lap',
  'pool',
  '10k',
  'ride',
  'done',
  'pick',
  'gym',
  'membership',
  'form'],
 ['cotd',
  'polar',
  'bear',
  'climb',
  'race',
  'angri',
  'polar',
  'bear',
  'climb',
  'race',
  'polar',
  'bear',
  'live',
  'cold',
  'place',
  'look'],
 ['user', 'user', 'get', 'angri', 'muslim', 'assassin', '50', 'much'],
 ['happi', 'snappi', 'ðð¼', 'wait', 'footbal', 'footbal', 'snapchat'],
 ['friday', 'miss', 'fringesqcbagssumm', 'ððððððó¾ð'],
 ['nochebuena', 'lasvega', 'usa', 'la', 'vega', 'strip'],
 ['fleurett', 'ðð', 'instaboyinstamansefieseptumfriend', 'smilesblackandwhit'],
 ['sad',
  'branch',
  'itâ',
  'raini',
  'day',
  'write',
  'tear',
  'fli',
  'bird',
  'haiku',
  '3line',
  'micropoetri'],
 ['yeah', 'new', 'button', 'mail', 'ð', 'pretti', 'jewelrymak', 'button'],
 ['user',
  'driver',
  'hit',
  'femal',
  'moos',
  'river',
  'rd',
  'weston',
  'moos',
  'kill',
  'driver',
  'ok',
  'crew',
  'remov',
  'anim'],
 ['afterpa',
  'made',
  'japan',
  'ï¼madeinjapan',
  'eo',
  'ï¼cute',
  'fun',
  'cawaii',
  'love',
  'strawberri',
  'tomato'],
 ['peopl',
  'arent',
  'protest',
  'trump',
  'republican',
  'wonthey',
  'trump',
  'fuher',
  'ampâ'],
 ['need', 'find', 'way', 'spend', 'time', 'alway', 'mind', 'boy', 'guy', 'â'],
 ['146604726015',
  'updat',
  'social',
  'analyt',
  'photooftheday',
  'iger',
  'like'],
 ['anyon',
  'know',
  'date',
  'doj',
  'fbi',
  'becam',
  'corrupt',
  'emailg',
  'hillary2016',
  'shame',
  'disgrac',
  'ridicul'],
 ['stupid',
  'make',
  'even',
  'negligencewhi',
  'put',
  'sachintendulkar',
  'instal',
  'u',
  'go',
  'take'],
 ['ððððââï',
  'ãããã',
  'bihdayð',
  '21thbihday',
  'ð',
  'bestfriend',
  'ð',
  'loveð¼'],
 ['user',
  'ð',
  'impoant',
  'thing',
  'enjoy',
  'life',
  'itâ',
  'matter',
  'life',
  'sho',
  'pooh4u'],
 ['happi',
  'bihday',
  'chri',
  'evansððððððð',
  'great',
  'actor',
  'human',
  'ððð³ðððððð',
  'chrisevan',
  'bihdayâ'],
 ['hea',
  'thought',
  'prayer',
  'go',
  '50',
  'peopl',
  'murder',
  'gay',
  'nightclub',
  'florida'],
 ['user',
  'demo',
  'guitar',
  'new',
  'album',
  'newalbum',
  'indi',
  'guitar',
  'echobelli'],
 ['retweet',
  'lion',
  'pro',
  'user',
  'tgif',
  'webmaret',
  'seo',
  'commun',
  'manag',
  'weekend'],
 ['â',
  'nzdusd',
  'target',
  '100',
  'week',
  'sma',
  '07190',
  'blog',
  'silver',
  'gold',
  'forex'],
 ['user',
  'ive',
  'pretti',
  'bad',
  'bihday',
  'week',
  'far',
  'worst',
  'ever',
  'ð',
  'bihdayweeksuck',
  'bithday27',
  'tâ'],
 ['bless', 'work', 'sa', 'best', 'lead', 'ladiesðð'],
 ['happiest',
  'place',
  'eah',
  'ð',
  'disneysmagickingdom',
  'disney',
  'magickingdom',
  'disneyland',
  'orlandoâ'],
 ['kinda', 'among', 'human'],
 ['found',
  'user',
  'user',
  'id',
  'exclaim',
  'user',
  'gr8',
  'blain',
  'hair',
  'nite',
  'ð'],
 ['user',
  'lt3',
  'listen',
  'beauti',
  'best',
  'friend',
  'user',
  'sing',
  'amaz',
  'voic',
  'lt3',
  'lt3',
  'lt3',
  'lt3',
  '17'],
 ['n',
  'healthi',
  'freedom',
  'effo',
  'present',
  'mere',
  'mean',
  'effo',
  'store',
  'past',
  'â',
  'theodor',
  'rooseveltâ'],
 ['know',
  'yall',
  '2',
  'aint',
  'go',
  'know',
  'love',
  'commit',
  'trust',
  'faith'],
 ['ye',
  'call',
  'michelleobama',
  'gorilla',
  'racist',
  'long',
  'thought',
  'black',
  'peopl',
  'betâ'],
 ['newarkfestiv', 'us', 'year', 'wait', 'show', 'sta', '3rd', 'year', 'run'],
 ['internet', 'broken', 'cant', 'watch', 'netflix', 'mochithepug', 'puglif'],
 ['user', 'user', 'user', 'thatthen', 'whatbusi', 'usual'],
 ['hbd',
  'dick',
  'suckin',
  'tequila',
  'lovin',
  'slut',
  'wouldnt',
  'want',
  'u',
  'way',
  'ðð',
  'justalil',
  'butstillontim'],
 ['smaller',
  'hand',
  'show',
  'barri',
  'probabl',
  'lie',
  'knick',
  'game',
  'suck',
  'golfâ'],
 ['good',
  'morn',
  'friday',
  'everyon',
  'weekend',
  'goodmorn',
  'friday',
  'girl',
  'love',
  'florida'],
 ['challeng', 'aap', 'claim', '70', 'punjabi', 'drugaddict', 'dare', 'prove'],
 ['tracerequest',
  'send',
  'deepest',
  'condol',
  'orlando',
  'gay',
  'famili',
  'zimbabw',
  'gay',
  'commun',
  'hea',
  'touch'],
 ['new', 'selfi', 'ââ', 'guy', 'mato', 'chapon'],
 ['saturday', 'afternoon', 'chi', 'meet', 'friend', 'user', 'user', 'user'],
 ['model', 'love', 'u', 'take', 'u', 'time', 'urð', 'ðððð', 'ððð'],
 ['so', 'nut', 'amp', 'bolt', 'bloke'],
 ['aww', 'yeah', 'good', 'bing', 'bong', 'bing', 'bong'],
 ['dawn',
  '2',
  'month',
  'see',
  'user',
  'live',
  'excit',
  'ððð',
  'vfest',
  'summer'],
 ['user',
  'happi',
  '35th',
  'bihday',
  'shane',
  'robe',
  'watson',
  'bihday',
  'shane',
  'watson',
  'australia',
  'cricker'],
 ['user',
  'user',
  'point',
  'one',
  'finger',
  'user',
  'million',
  'point',
  'right',
  'back',
  'jewishsupremacist'],
 ['sad',
  'hear',
  'announc',
  'say',
  'may',
  'move',
  'player',
  'one',
  'two',
  'lead',
  'whoknow'],
 ['radio1', 'im', 'go', 'coldplay', 'tonight', 'oh', 'ye'],
 ['u', 'think', 'like', 'god', 'come', 'god', 'keep'],
 ['user',
  'terrorist',
  'constitut',
  'right',
  'anoth',
  'excus',
  'republican',
  'appeas',
  'nra',
  'gun',
  'control',
  'measur'],
 ['user', 'user', 'gloucesterrugbi'],
 ['user', 'sad', 'user', 'happen'],
 ['everyon',
  'everyth',
  'sad',
  'togeth',
  'alon',
  'fine',
  'dandi',
  'lone',
  'exuber',
  'depress',
  'halfful',
  'halfempti'],
 ['mikeashley',
  'sposdirectsham',
  'perhaps',
  'good',
  'exampl',
  'need',
  'protect',
  'workersright',
  'within',
  'europ',
  'euref',
  'remain'],
 ['angri',
  'bird',
  'stella',
  'bad',
  'princess',
  'bird',
  'stella',
  'bad',
  'princess',
  'birdsstellabadprincess',
  'time',
  'post',
  'wedâ'],
 ['check', 'user', 'incred', 'made', 'great', 'memori', 'great', 'peopl'],
 ['saw', 'shi', 'last', 'night', 'said', 'rip', 'care', 'realli'],
 ['user',
  'hilari',
  'user',
  'im',
  'alreadi',
  'block',
  'user',
  'ask',
  'one',
  'paicularli',
  'difficult',
  'question',
  'user'],
 ['devast', 'news', 'hea', 'goe', 'victim', 'famili', 'orlando', 'heabreak'],
 ['happi',
  'state',
  'arriv',
  'manner',
  'travel',
  'margaret',
  'lee',
  'runbeck',
  'happi',
  'quot',
  'inspir'],
 ['safe', 'way', 'heal', 'acn', 'altwaystoh', 'healthi', 'heal'],
 ['creat',
  'right',
  'beat',
  'makingbeat',
  'thursday',
  'work',
  'istandard',
  'akaiproâ'],
 ['wed',
  'number',
  '10',
  'ðððððð¾ð¾',
  'wed',
  'weddingpay',
  'love',
  'forev',
  'weddingdressâ'],
 ['look',
  'forward',
  'attend',
  'cipd',
  'ireland',
  'confer',
  'amp',
  'workshop',
  'cpd',
  'onemoreday',
  'user',
  'user'],
 ['final',
  'reach',
  '200',
  'follow',
  'twitch',
  'follow',
  'hypu',
  'stream',
  'tomorrow',
  'â'],
 ['word',
  'r',
  'free',
  'u',
  'use',
  'em',
  'cost',
  'verbal',
  'abus',
  'hu',
  'love',
  'adult',
  'teen',
  'user'],
 ['countri',
  'went',
  'last',
  'year',
  'see',
  'peopl',
  'bring',
  'bomb',
  'stadium',
  'amp',
  'come',
  'everyth',
  'footbal'],
 ['thank', 'cat', 'thank', 'posit'],
 ['time',
  'eat',
  'bae',
  'swalscha',
  'ðâð',
  'dejeun',
  'lunch',
  'happi',
  'love',
  'amoureuxâ'],
 ['ilovethesecret',
  'lawofattract',
  'quiz',
  'love',
  'happi',
  'motiv',
  'success',
  'joy',
  'lifeâ'],
 ['might', 'libtard', 'libtard', 'sjw', 'liber', 'polit'],
 ['go',
  'pole',
  'bgp',
  'rozthediva',
  'blackgirlspol',
  'bodyandpol',
  'live',
  'love',
  'â'],
 ['argentina2015',
  'attack',
  'bull',
  'game',
  '3d',
  'realli',
  'think',
  'head',
  'empti',
  'around',
  'citi',
  'side'],
 ['selfserv',
  'hypocrit',
  'alway',
  'keep',
  'eye',
  'bounc',
  'ball',
  'nimrod',
  'presid'],
 ['nohcarolina', 'bull', 'domin', 'bull', 'direct', 'whatev', 'want', 'whe'],
 ['build',
  'polar',
  'bear',
  'climb',
  'race',
  'angri',
  'polar',
  'bear',
  'climb',
  'race',
  'polar',
  'bear',
  'live',
  'cold',
  'place',
  'loo'],
 ['user', 'user', 'want', 'reelect', 'money', 'ksleg'],
 ['hea',
  'orlando',
  'right',
  'truli',
  'imagin',
  'could',
  'easili',
  'happen',
  'anywher'],
 ['alreemgroup',
  'aly_alshahawi',
  'ad',
  'cute',
  'summer',
  'photographerdubai',
  'sun',
  'hair',
  'mydubaiâ'],
 ['seem', 'like', 'place', 'action', 'montreal'],
 ['user', 'old', 'wash'],
 ['spirit', 'i_am', 'posit', 'affirm'],
 ['thank', 'enteain', 'thank', 'posit'],
 ['user', 'user', 'user', 'show', 'truli', 'bad', 'brisban'],
 ['user', 'cant', 'wait', 'wimbledon2016'],
 ['happi',
  'man',
  'success',
  'model',
  'entrepreneur',
  'speaker',
  'ff',
  'fresh',
  'confid',
  'fashionâ'],
 ['gala',
  'moment',
  'day',
  'kid',
  'bipolar',
  'frikiegirl2016',
  'lucki',
  'chinatown',
  'mall',
  'binondoâ'],
 ['realli',
  'take',
  'piss',
  'im',
  'angri',
  'goe',
  'show',
  'valu',
  'isnt',
  'complet',
  'utter',
  'moron'],
 ['user', 'take', 'trash', 'america', 'vote', 'hate', 'vote', 'vote', 'votâ'],
 ['father', 'day', 'amaz', 'dad', 'give', 'much', 'famili', 'enjoy'],

In [23]:
stm=[" ".join(i) for i in stemed_data]

In [24]:
pip install scikit-learn

Requirement already satisfied: scikit-learn in c:\users\anjan\appdata\local\programs\python\python312\lib\site-packages (1.5.1)
Requirement already satisfied: numpy>=1.19.5 in c:\users\anjan\appdata\local\programs\python\python312\lib\site-packages (from scikit-learn) (2.0.1)
Requirement already satisfied: scipy>=1.6.0 in c:\users\anjan\appdata\local\programs\python\python312\lib\site-packages (from scikit-learn) (1.14.0)
Requirement already satisfied: joblib>=1.2.0 in c:\users\anjan\appdata\local\programs\python\python312\lib\site-packages (from scikit-learn) (1.4.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in c:\users\anjan\appdata\local\programs\python\python312\lib\site-packages (from scikit-learn) (3.5.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 24.0 -> 25.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [25]:
from sklearn.feature_extraction.text import CountVectorizer

In [26]:
cv=CountVectorizer(max_features=2000)

In [27]:
vc=cv.fit(stm)

In [28]:
import pickle
with open("vectorizer.pickle","wb") as vcfile:
    pickle.dump(vc,vcfile)

In [29]:
x=vc.transform(stm).toarray()

In [30]:
x

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [31]:
y=df["label"]

In [32]:
from sklearn.naive_bayes import MultinomialNB

In [33]:
mb = MultinomialNB()

In [34]:
mb.fit(x,y)

MultinomialNB()

In [35]:
import pickle
with open("model.pickle","wb") as model_file:
    pickle.dump(mb,model_file)